version: "3.9"

services:
  mysql83:
    container_name: "${COMPOSE_MYSQL_NAME:-utilities-mysql-8-3}"
    image: mysql:8.3.0
    volumes:
      - ./mysql/8.3/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--default-authentication-plugin=mysql_native_password"
    restart: unless-stopped